name: Build gopls-deps

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '0.14.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      
    - name: Setup Go
      uses: actions/setup-go@v4.1.0

    - name: Build and package dependencies
      run: |
        cd gopls
        GOMODCACHE="${PWD}"/go-mod go mod download -modcacherw
        XZ_OPT='-T0 -9' tar -acf "gopls-${{ github.event.inputs.version }}-deps.tar.xz" go-mod
    - name: Create GitHub Release
      run: |
        cd gopls
        gh release create "${{ github.event.inputs.version }}" "gopls-${{ github.event.inputs.version }}-deps.tar.xz" -t "Release ${{ github.event.inputs.version }}" -n "gopls ${{ github.event.inputs.version }} dependencies"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
